#!/usr/bin/env bash
# 45-macos — the same look on a Mac: zsh prompt + colors, the login banner,
#            and a Terminal.app profile generated from the Konsole one.
#
# Numbered 45 so it sits next to konsole (40): both install the terminal theme,
# just for different terminals. Nothing else in the repo is shared — this module
# is a no-op on Linux and every Linux module is a no-op here.
#
# Three things differ from the Linux path, and all three are forced:
#
#   shell     macOS logs in with zsh, not bash, so the rc is a zsh rewrite
#             (templates/zsh/synth.zshrc) rather than a copy of synth.rc. The
#             banner likewise: macOS ships bash 3.2, which has no associative
#             arrays, so banner.zsh rebuilds the font as a case statement.
#
#   terminal  Terminal.app has no Konsole-style config file. Its profiles live
#             in its preferences domain, with every colour as an
#             NSKeyedArchiver blob, so the profile is generated by
#             tools/gen-terminal-profile.py and installed with `defaults`
#             rather than copied into place. The template IS checked in, so
#             installing needs no python.
#
#   font      no fontconfig and no apt. Hack comes from a Homebrew cask, and
#             failing to get it is a warning, not an error: Terminal silently
#             falls back to Menlo, which is a worse-looking theme rather than a
#             broken one.

SYNTH_ZSHRC="$HOME/.synthwave-shell.zshrc"
BANNER_ZSH="$HOME/.synthwave-banner.zsh"

TERM_DOMAIN="com.apple.Terminal"
TERM_PROFILE="Synthwave"
TERM_PREFS="$HOME/Library/Preferences/com.apple.Terminal.plist"

module_macos() {
    head1 "macos terminal"

    require_macos "the macOS terminal theme" || return 0

    # Advisory, never fatal — see the header note on fonts.
    if font_installed Hack; then
        skip "font present: Hack"
    else
        need_casks font-hack \
            || warn "Hack not installed; Terminal will fall back to Menlo"
    fi

    install_file "$TEMPLATE_DIR/zsh/synth.zshrc" "$SYNTH_ZSHRC" symlink || return 1
    install_file "$TEMPLATE_DIR/zsh/banner.zsh"  "$BANNER_ZSH"  symlink || return 1

    local zshrc="$HOME/.zshrc"
    if [ ! -f "$zshrc" ]; then
        warn "~/.zshrc does not exist; creating one that only loads synth.zshrc"
    fi

    _strip_legacy_zsh_lines "$zshrc"

    # Appended, so it lands after `source $ZSH/oh-my-zsh.sh`. Order is not
    # cosmetic: oh-my-zsh sets its own PROMPT from $ZSH_THEME and exports its
    # own LS_COLORS. Loading synth.zshrc before it would leave the theme's
    # prompt in place and our palette discarded, which reads as "the install
    # did nothing".
    #
    # Both lines are guarded on the file existing, matching the bash module, so
    # `--only macos` after a manual `rm` degrades to an inert line rather than
    # a shell that errors on every new tab.
    ensure_block "$zshrc" \
        '# Synthwave shell colors. Loaded after oh-my-zsh so its prompt and LS_COLORS win.' \
        '[ -f "$HOME/.synthwave-shell.zshrc" ] && . "$HOME/.synthwave-shell.zshrc"' \
        '# Login banner. Sourced after the rc; no-op when the banner is not installed.' \
        '[ -f "$HOME/.synthwave-banner.zsh" ] && . "$HOME/.synthwave-banner.zsh"'

    _install_terminal_profile || return 1
}

# The rc and banner started life as hand-added lines, from before the repo
# shipped either one. Drop any that live outside our markers: left in place the
# rc would be sourced twice (harmless but it re-runs all the zstyle setup) and
# the banner's second copy would print nothing at all, because
# SYNTHWAVE_BANNER_SHOWN is already set — which looks like the new one is
# broken. Matches on the filename rather than a `source` pattern, because these
# lines are written guarded (`[ -f ... ] && . ...`), not as a bare source.
_strip_legacy_zsh_lines() {
    local file="$1" tmp n
    [ -f "$file" ] || return 0

    n="$(awk -v b="$BLOCK_BEGIN" -v e="$BLOCK_END" '
        index($0,b){inb=1} index($0,e){inb=0; next}
        !inb && /synthwave-shell\.zshrc|synthwave-banner\.zsh/ {c++}
        END{print c+0}
    ' "$file")"

    [ "$n" -eq 0 ] && return 0

    backup "$file"
    if [ "$DRY_RUN" = 1 ]; then
        printf '  %s$ remove %s legacy synthwave line(s) from ~/.zshrc%s\n' \
            "$C_DIM" "$n" "$C_OFF"
        return 0
    fi

    tmp="$(mktemp)"
    awk -v b="$BLOCK_BEGIN" -v e="$BLOCK_END" '
        index($0,b){inb=1; print; next}
        index($0,e){inb=0; print; next}
        inb { print; next }
        /synthwave-shell\.zshrc|synthwave-banner\.zsh/ { next }
        { print }
    ' "$file" > "$tmp" && mv "$tmp" "$file" || { rm -f "$tmp"; fail "strip legacy zsh lines"; return 1; }
    ok "removed $n legacy synthwave line(s) from ~/.zshrc"
}

# ---------- Terminal.app ----------
# Written with `defaults`, not by editing the plist in place. cfprefsd owns that
# file and caches it; a direct write is liable to be overwritten from the cache
# and needs a `killall cfprefsd` to take, which also discards every other app's
# pending preferences.
_install_terminal_profile() {
    local src="$TEMPLATE_DIR/terminal/$TERM_PROFILE.terminal"
    [ -f "$src" ] || { fail "missing template: $src (run tools/gen-terminal-profile.py)"; return 1; }

    if _terminal_profile_current "$src"; then
        skip "Terminal profile '$TERM_PROFILE' already current"
    else
        backup "$TERM_PREFS"
        if [ "$DRY_RUN" = 1 ]; then
            printf '  %s$ defaults write %s "Window Settings" -dict-add %s <%s>%s\n' \
                "$C_DIM" "$TERM_DOMAIN" "$TERM_PROFILE" "${src##*/}" "$C_OFF"
        else
            # -dict-add parses the file as a plist literal and merges it in as
            # one key, leaving every other profile in the domain untouched.
            defaults write "$TERM_DOMAIN" "Window Settings" \
                -dict-add "$TERM_PROFILE" "$(cat "$src")" \
                || { fail "defaults write failed for $TERM_PROFILE"; return 1; }
        fi
        ok "Terminal profile '$TERM_PROFILE' installed"
    fi

    # Two separate keys, and setting only one is the usual mistake: Default
    # governs new windows (cmd-N), Startup governs the window Terminal opens
    # when it launches. Miss Startup and every fresh launch comes up Basic.
    _terminal_default_set "Default Window Settings" || return 1
    _terminal_default_set "Startup Window Settings" || return 1

    if _terminal_running; then
        warn "Terminal is running — QUIT it completely (cmd-Q) and reopen."
        warn "  A new window or tab is NOT enough. The shell rc is read per"
        warn "  shell, so the prompt appears in a new tab immediately and it"
        warn "  looks like the theme landed; the window's colours and opacity"
        warn "  come from Terminal itself, which cached 'Window Settings' at"
        warn "  launch and will not see a profile added behind its back."
        warn "  Quitting ends anything running inside Terminal, this included."
    fi
}

# NOT `pgrep -x Terminal`, which is the obvious spelling and silently finds
# nothing in a restricted/sandboxed context — the warning above then never
# prints, in exactly the situation it exists for. Matching the bundle path out
# of `ps` works regardless, and is narrower than pgrep -f: it cannot be fooled
# by some unrelated process that merely has "Terminal" in its argv.
#
# `grep -c` and a count test, NOT the obvious `ps ... | grep -q`. common.sh sets
# `-o pipefail`, and grep -q exits the instant it matches, so ps is killed by
# SIGPIPE mid-write and exits 141. pipefail then reports the PIPELINE as failed
# on the strength of ps's status even though grep matched — a false negative
# that only shows up once the output is big enough for ps to still be writing,
# which `ps -A` on a real machine always is. grep -c reads to EOF, so ps always
# finishes cleanly.
_terminal_running() {
    [ "$(ps -Awwo comm= 2>/dev/null | grep -c '/Terminal\.app/Contents/MacOS/Terminal$')" -gt 0 ]
}

# True when the profile already in the domain matches the template exactly.
# Both sides are normalised through plutil first: the template is XML and what
# comes back out of the domain is re-serialised, so a byte compare of the raw
# forms would report drift on every run.
_terminal_profile_current() {
    local src="$1" dump have want got rc=1

    [ -x /usr/libexec/PlistBuddy ] || return 1

    dump="$(mktemp)"; have="$(mktemp)"; want="$(mktemp)"; got="$(mktemp)"
    if defaults export "$TERM_DOMAIN" "$dump" 2>/dev/null \
        && /usr/libexec/PlistBuddy -x -c "Print :'Window Settings':$TERM_PROFILE" "$dump" > "$have" 2>/dev/null \
        && plutil -convert xml1 -o "$want" "$src"  2>/dev/null \
        && plutil -convert xml1 -o "$got"  "$have" 2>/dev/null \
        && cmp -s "$want" "$got"; then
        rc=0
    fi
    rm -f "$dump" "$have" "$want" "$got"
    return $rc
}

_terminal_default_set() {
    local key="$1" cur
    cur="$(defaults read "$TERM_DOMAIN" "$key" 2>/dev/null || true)"
    if [ "$cur" = "$TERM_PROFILE" ]; then
        skip "$key already $TERM_PROFILE"
        return 0
    fi

    backup "$TERM_PREFS"
    if [ "$DRY_RUN" = 1 ]; then
        printf '  %s$ defaults write %s "%s" -string %s%s\n' \
            "$C_DIM" "$TERM_DOMAIN" "$key" "$TERM_PROFILE" "$C_OFF"
        return 0
    fi

    defaults write "$TERM_DOMAIN" "$key" -string "$TERM_PROFILE" \
        || { fail "defaults write $key"; return 1; }
    ok "$key = $TERM_PROFILE"
}
