#!/usr/bin/env bash
# 85-vscode — the Synthwave VS Code theme.
#
# The theme is generated by tools/gen-vscode-theme.py from three files that
# already exist here — the Plasma colour scheme, the vim colorscheme and the
# Konsole colorscheme — so the workbench matches Qt apps, syntax highlighting
# matches vim, and the integrated terminal matches Konsole. Do not hand-edit
# templates/vscode/.
#
# It is packed into a .vsix and installed with `code --install-extension`,
# NOT by copying the directory into ~/.vscode/extensions/. Copying looks like
# it works — the folder is there, with the right name — and does nothing:
# modern VS Code loads only what is listed in that directory's own
# extensions.json, which it writes itself. A hand-placed folder never appears
# in `code --list-extensions` and the theme never reaches the picker, with no
# error anywhere. Building the vsix needs no npm or vsce; it is a zip with two
# bits of metadata, see tools/make-vsix.py.
#
# Installing the extension and SELECTING it are separate steps: selecting
# writes to your settings.json.

VSCODE_EXT_ID="ubu-setup.synthwave-theme"
VSCODE_EXT_VERSION="1.0.0"
VSCODE_THEME_LABEL="Synthwave"

module_vscode() {
    head1 "vscode theme"

    local src="$TEMPLATE_DIR/vscode/synthwave-theme"
    [ -d "$src" ] || { fail "vscode theme template missing: $src"; return 1; }

    if ! command -v code >/dev/null 2>&1; then
        skip "vscode not installed; skipping"
        return 0
    fi

    _vscode_validate "$src" || return 1
    _vscode_install "$src" || return 1

    if [ "${VSCODE_APPLY:-0}" = 1 ]; then
        _vscode_select
    else
        skip "not selecting it (pass --apply-vscode, or pick $VSCODE_THEME_LABEL in the theme list)"
    fi

    if pgrep -x code >/dev/null 2>&1; then
        warn "vscode is running — reload the window (Ctrl+Shift+P, Reload Window)"
    fi
}

# A theme whose JSON does not parse installs silently and then simply never
# appears in the picker, with the reason buried in the extension host log.
_vscode_validate() {
    local src="$1"
    command -v python3 >/dev/null 2>&1 || { skip "python3 absent; skipping theme validation"; return 0; }

    local out
    if ! out="$(python3 - "$src" "$VSCODE_THEME_LABEL" <<'PY' 2>&1
import json, os, sys
src, label = sys.argv[1], sys.argv[2]
errs = []
try:
    pkg = json.load(open(os.path.join(src, 'package.json')))
except Exception as e:
    print(f'package.json does not parse: {e}'); sys.exit(1)

themes = pkg.get('contributes', {}).get('themes', [])
if not themes:
    errs.append('package.json contributes no themes')
for t in themes:
    if t.get('label') != label:
        errs.append(f'theme label is {t.get("label")!r}, expected {label!r}')
    rel = t.get('path', '')
    p = os.path.join(src, rel)
    if not os.path.exists(p):
        errs.append(f'theme path {rel} does not exist')
        continue
    try:
        json.load(open(p))
    except Exception as e:
        errs.append(f'{rel} does not parse: {e}')
for e in errs:
    print(e)
sys.exit(1 if errs else 0)
PY
    )"; then
        fail "vscode theme failed validation:"
        printf '%s\n' "$out" | sed 's/^/      /' >&2
        return 1
    fi
    skip "theme json is well-formed"
    return 0
}

_vscode_install() {
    local src="$1"

    # `code --list-extensions` is the only honest test of whether it is
    # installed: the directory existing proves nothing, which is the whole
    # reason this module packs a vsix.
    if code --list-extensions --show-versions 2>/dev/null \
         | grep -qx "$VSCODE_EXT_ID@$VSCODE_EXT_VERSION"; then
        skip "$VSCODE_EXT_ID@$VSCODE_EXT_VERSION already installed"
        return 0
    fi

    if [ "$DRY_RUN" = 1 ]; then
        printf '  %s$ pack %s into a vsix and code --install-extension it%s\n' \
            "$C_DIM" "${src/#$REPO_DIR\//}" "$C_OFF"
        ok "would install $VSCODE_EXT_ID@$VSCODE_EXT_VERSION"
        return 0
    fi

    local vsix="$STATE_DIR/synthwave-theme-$VSCODE_EXT_VERSION.vsix"
    mkdir -p "$STATE_DIR"
    if ! python3 "$REPO_DIR/tools/make-vsix.py" "$src" "$vsix" >/dev/null; then
        fail "could not build $vsix"
        return 1
    fi

    # --force so a rebuilt theme at the same version replaces the old one
    # instead of being refused as already present.
    if ! code --install-extension "$vsix" --force >/dev/null 2>&1; then
        fail "code --install-extension failed for $vsix"
        return 1
    fi

    if code --list-extensions 2>/dev/null | grep -qx "$VSCODE_EXT_ID"; then
        ok "installed $VSCODE_EXT_ID@$VSCODE_EXT_VERSION"
    else
        fail "vsix installed but $VSCODE_EXT_ID is still not registered"
        return 1
    fi
}

# Set workbench.colorTheme in the user's settings.json.
#
# That file is VS Code's, not ours, and it is JSONC — comments and trailing
# commas are legal in it. Rewriting one that has comments would strip them,
# so anything this cannot parse as strict JSON is left alone with an
# explanation rather than mangled.
_vscode_select() {
    local settings="$HOME/.config/Code/User/settings.json"

    if [ ! -f "$settings" ]; then
        if [ "$DRY_RUN" = 1 ]; then
            printf '  %s$ create %s with the theme selected%s\n' "$C_DIM" "${settings/#$HOME/\~}" "$C_OFF"
        else
            mkdir -p "$(dirname "$settings")"
            printf '{\n    "workbench.colorTheme": "%s"\n}\n' "$VSCODE_THEME_LABEL" > "$settings"
        fi
        ok "${settings/#$HOME/\~} created with $VSCODE_THEME_LABEL selected"
        return 0
    fi

    # Two passes on purpose. The first only reports what would happen, so the
    # backup can be taken BEFORE anything is written — backing up afterwards
    # would preserve the already-modified file and be worthless. It also keeps
    # a settled system from minting a backup directory it does not need.
    local status
    status="$(_vscode_settings_pass "$settings" 1)"

    case "$status" in
        ALREADY) skip "settings.json already selects $VSCODE_THEME_LABEL"; return 0 ;;
        UNPARSEABLE)
            warn "settings.json has comments or is not a JSON object — not rewriting it"
            warn "  set it by hand: \"workbench.colorTheme\": \"$VSCODE_THEME_LABEL\""
            return 0
            ;;
        SET) : ;;
        *) fail "could not read settings.json"; return 1 ;;
    esac

    backup "$settings"
    if [ "$DRY_RUN" != 1 ]; then
        status="$(_vscode_settings_pass "$settings" 0)"
        [ "$status" = "SET" ] || { fail "settings.json write failed ($status)"; return 1; }
    fi
    ok "settings.json workbench.colorTheme=$VSCODE_THEME_LABEL"
}

# check_only=1 reports without writing; 0 writes.
_vscode_settings_pass() {
    local settings="$1" check_only="$2"
    python3 - "$settings" "$VSCODE_THEME_LABEL" "$check_only" <<'PY'
import json, sys
path, label, check_only = sys.argv[1], sys.argv[2], sys.argv[3] == '1'
try:
    data = json.loads(open(path).read())
except Exception:
    print('UNPARSEABLE'); sys.exit(0)
if not isinstance(data, dict):
    print('UNPARSEABLE'); sys.exit(0)
if data.get('workbench.colorTheme') == label:
    print('ALREADY'); sys.exit(0)
data['workbench.colorTheme'] = label
if not check_only:
    with open(path, 'w') as f:
        json.dump(data, f, indent=4)
        f.write('\n')
print('SET')
PY
}
